# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`
   
#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

In [7]:
a=np.zeros((10))
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

In [11]:
a[4]=1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [4]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [27]:
d = np.array([1,2,0,0,4,0])
np.nonzero(d)

(array([0, 1, 4]),)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [34]:
np.random.random((3,3,3))

array([[[0.78892674, 0.42651118, 0.95992139],
        [0.61688619, 0.53293455, 0.45837708],
        [0.05496544, 0.07521363, 0.60405422]],

       [[0.4749108 , 0.44123018, 0.07754322],
        [0.63915377, 0.458136  , 0.47849947],
        [0.65205263, 0.87614367, 0.72307104]],

       [[0.28365356, 0.39776758, 0.12030565],
        [0.46503554, 0.32180738, 0.30812386],
        [0.86840195, 0.27425713, 0.23054661]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [60]:
a=np.random.random((10,10))
print('minimum is: ', np.amin(a))
print('maximum is: ', np.amax(a))

minimum is:  0.002071334623689136
maximum is:  0.9860679877563902


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [61]:
a = np.random.randint(100, size=30)
np.mean(a)

43.233333333333334

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [14]:
np.diag([1,2,3,4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [15]:
a=np.random.randint(100, size=25).reshape((5,5))

a_m=np.mean(a)
a_s=np.std(a)

b= (a-a_m)/a_s

b

array([[-1.28654438, -0.69638641,  1.2806428 , -0.04721264,  0.86753222],
       [-1.43408387, -0.25376793,  1.1626112 , -0.31278372, -1.34556017],
       [ 0.45442164, -0.43081532, -0.57835481, -1.19802068,  1.1921191 ],
       [-0.54884691,  0.83802432,  0.24786635,  1.2511349 ,  1.2806428 ],
       [ 1.1331033 ,  0.54294533, -1.46359177, -1.61113126,  0.95605591]])

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [23]:
a=np.random.randint(100, size=25).reshape((5,5))
b=np.random.randint(100, size=25).reshape((5,5))


np.intersect1d(a,b)

array([10, 11, 14, 68, 95])

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [28]:
a=np.random.randint(100, size=10)
np.sort(a)                

array([ 2, 18, 24, 43, 44, 62, 66, 70, 73, 97])

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [31]:
a=np.random.randint(100, size=10)
print(a)
a[np.argmax(a)]=0
print(a)

[45 61  6 54 64 56 44 11  1 36]
[45 61  6 54  0 56 44 11  1 36]


#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [33]:
import numpy as np

a=np.random.randint(100, size=9).reshape((3,3))
print(a)
b=np.mean(a,axis=1,keepdims=True)
print(b)

c=a-b
c


[[54 47 42]
 [80 65 90]
 [31 85  0]]
[[47.66666667]
 [78.33333333]
 [38.66666667]]


array([[  6.33333333,  -0.66666667,  -5.66666667],
       [  1.66666667, -13.33333333,  11.66666667],
       [ -7.66666667,  46.33333333, -38.66666667]])

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [36]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print(Z[np.argpartition(-Z,n)[:n]])


[9995 9997 9999 9998 9996]


18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
hint: np.where

In [39]:
a=np.random.randint(0,10,size=(5,3))
a


array([[0, 9, 7],
       [0, 5, 9],
       [9, 6, 8],
       [1, 9, 4],
       [8, 6, 7]])